### PR TITLE
More refined syntax check w/ #AutoIt3Wrapper_AU3Check_Parameters

### PR DESCRIPTION
**Pull request by vanowm**
same as #215 but with 
ability overwrite settings via #AutoIt3Wrapper_AU3Check_Parameters

### CODE REVIEW

**Comment by loganch** [comment]
Messed with it a little bit and I think there's a small issue that the flags actually include a space, e.g., the flag to enable local var used in global scope is "-w 4", so the comma separation in the initial variable and the regex/logic to parse from the script need to be adjusted.

**Comment by vanowm** [comment]
I don't believe I understand you...which variable and regex you are referring to?

**Comment by Sven-Seyfert** [comment]
Hi @loganch, hi @vanowm 👋 .

> I don't believe I understand you...which variable and regex you are referring to?

I guess [line 48](https://github.com/loganch/AutoIt-VSCode/pull/216/files#diff-41610ea8b06474549c4f312fdc247353665bc6434811db5418853bf57137bba5R48) is meant by Logan. But I also don't see the problem.

The RegEx pattern `(-w-?)\s+([0-9]+)` matches the following variants, as far as I can say and understood:

### As image (visualization)

grafik

### As text form

``` autoit
;~ ----
;~ Okay
;~ ----
#AutoIt3Wrapper_AU3Check_Parameters=-d -w 1 -w 2 -w 3 -w 4 -w 5 -w 6 -w 7

#AutoIt3Wrapper_AU3Check_Parameters=-d -w 1 -w 2 -w    3 -w 4 -w 5 -w 6 -w 7

#AutoIt3Wrapper_AU3Check_Parameters=-d -w 1 -w 2 -w- 3 -w 4 -w 5 -w 6 -w 7

#AutoIt3Wrapper_AU3Check_Parameters=-d -w 1 -w 2 -w-   3 -w 4 -w 5 -w 6 -w 7

;~ --------
;~ Not okay
;~ --------
#AutoIt3Wrapper_AU3Check_Parameters=-d -w 1 -w 2 -w3 -w 4 -w 5 -w 6 -w 7

#AutoIt3Wrapper_AU3Check_Parameters=-d -w 1 -w 2 -w-3 -w 4 -w 5 -w 6 -w 7

#AutoIt3Wrapper_AU3Check_Parameters=-d -w 1 -w 2 w 3 -w 4 -w 5 -w 6 -w 7

#AutoIt3Wrapper_AU3Check_Parameters=-d -w 1 -w 2 w- 3 -w 4 -w 5 -w 6 -w 7
```

My manual tests for this PR were successful 😀 . But I hope I do not miss something 🤔 ?

Best regards
Sven

**Comment by loganch** [comment]
No, I was mistaken, merging it now.

**Pull request merged**
