### PR TITLE
Add insert header functionality

### PR DESCRIPTION
**Pull request by Danp2**
This is a first attempt to mimic the InsertFunctionHeader feature from Scite. I'm sure that it can be further improved, but felt this was a good starting point for discussions.

### CODE REVIEW

**Comment by Danp2** [comment]
Hi @Sven-Seyfert,

Yes... it should either be removed completely or updated to match the current Autoit header standard. 

Let's see what @loganch has to say about this.

Dan

**Comment by loganch** [comment]
Hmmm, the way this generates the header is superior but I kinda want to keep an updated snippet in as an option.

@Danp2, ByRef parameters don't seem to parse properly:
image
Here's from the UDF-spec wiki page:
image

What do you think about removing the "None" and "No" for the Return value and Example fields? The template has them blank and we're making assumptions with the current output.

**Comment by Danp2** [comment]
> ByRef parameters don't seem to parse properly

Good catch! I look into that in a bit.

> What do you think about removing the "None" and "No" for the Return value and Example fields? 

I think it would be fine to drop the 'None' for return value. Per the [specs](https://www.autoitscript.com/wiki/UDF-spec#Functions), `Examples` is supposed to be either Yes or No. I figured that No would be a good default value.

P.S. Just checked and the Scite version of this uses None / No as defaults

**Comment by loganch** [comment]
Oh let's leave it to match SciTE, then.

**Comment by Danp2** [comment]
@loganch Take a look at the latest commit. FYI, [in/out] is generated by the Scite functionality so that is done here as well.

A few minor issues still remain --

- Author - Do we want to add a setting for this or does one already exist?
- Syntax line - Scite implementation adds square brackets around the optional parameters

**Comment by loganch** [comment]
There's no setting author setting currently, but I investigated and in SciTE\properties\au3.properties there's a "UDFCreator" field that lets the user set the name. I think we should add that to the config (default to "Your Name" like SciTE) and have the function pull from there.

It'd be nice to get the square brackets for optional parameters to match the way Syntax is presented in the docs, signatures and hovers.

**Comment by Danp2** [comment]
@loganch Please retest when you have a moment

**Comment by loganch** [comment]
Looks great!

**Pull request merged**
