### PR TITLE
work around for #209

### PR DESCRIPTION
**Pull request by vanowm**
This patch `forcibly` merging default settings into global config. It doesn't overwrite any modified settings.
Would be nice add some cleanup on extension disable/uninstall, but I couldn't find a way to do so.

Fix for #209

### CODE REVIEW

**Comment by loganch** [comment]
Nice catch/find, you're not able to save the state of global config before changes and then undo the changes through the `deactivate()` function in extension.js?

**Comment by vanowm** [comment]
Didn't know about that function. How do we test it though? (I mean besides directly calling the function) The extension is not in the list of installed extensions, so I can't disable or uninstall it...

**Comment by vanowm** [comment]
It seems [not possible](https://github.com/microsoft/vscode/issues/105484#issuecomment-683279949) within this function.

**Comment by loganch** [comment]
Yikes, that's unfortunate.

**Pull request merged**
