### PR TITLE
Fix filepath error #20

### PR DESCRIPTION
**Pull request by Worlor**

### CODE REVIEW

**Comment by loganch** [comment]
In my testing, removing the if statement breaks include statements that have the full path. For instance, a script on the C: drive with #include "D:\dev\AutoIt\tracking.au3".

**Comment by Worlor** [comment]
Yes, it's fixed

**Comment by Worlor** [comment]
Yes, I fixed it and adjusted my code
Javascript is not my cup of tea :laughing:

**Comment by loganch** [comment]
Good stuff, thank you!

**Pull request merged**
